WORDS_DATA = {
    "Unit 9": {
        "architecture": "arxitektor",
        "Englishman": "ingliz",
        "food": "ovqat",
        "generally": "umuman olganda",
        "kilometre": "kilometr",
        "of course": "albatta",
        "polite": "xushmuomala",
        "prefer": "afzal koʻrmoq",
        "romantic": "romantik",
        "tall": "baland",
        "true": "toʻgʻri",
        "wet": "hoʻl, nam",
        "careful": "ehtiyotkor",
        "safe": "xavfsiz",
        "accent": "aksent, talaffuz",
        "artists": "artistlar",
        "clubs": "klublar",
        "cool": "yaxshi, ajoyib",
        "fashion": "moda",
        "hundreds": "yuzlab",
        "jewellery": "zargarlik buyumlari",
        "market": "bozor",
        "Metro": "metro",
        "nightclub": "tungi klub",
        "north": "shimol",
        "take place": "joy olmoq",
        "tattoo": "tatuirovka",
        "public transport": "transport",
        "transport": "transport",
        "celebrities": "mashhurlar",
        "central": "markaziy",
        "loud": "shovqinli",
        "palace": "saroy",
        "quieter": "tinchroq",
        "somewhere": "qayerdadir",
        "tourist attraction": "turistik joy",
        "air": "havo",
        "area": "joy",
        "banks": "banklar",
        "blossom": "yapon daraxti",
        "capital city": "poytaxt shahar",
        "change": "oʻzgarmoq",
        "cherry": "olcha",
        "climate": "iqlim",
        "coast": "qirgʻoq",
        "colonial": "koloniya",
        "commercial centres": "savdo markazlari",
        "commuter": "qatnovchilar",
        "crowded": "toʻla",
        "culture": "madaniyat",
        "earthquake": "zilzila",
        "east": "sharq",
        "electricity": "elektr energiyasi",
        "elegant": "nafis",
        "emperor": "imperator",
        "empire": "imperiya",
        "experience": "tajriba",
        "extreme": "keskin, juda",
        "fishing": "baliqchilik",
        "foreigners": "chet elliklar",
        "gold": "oltin",
        "goods": "narsalar",
        "handicrafts": "hunarmandchilik",
        "headquarters": "shtab-kvartirasi",
        "high-class": "yuqori sinf",
        "huge": "ulkan",
        "humid": "nam",
        "independence": "mustaqillik",
        "industry": "sanoat",
        "invade": "bosib olmoq",
        "latest": "soʻnggi",
        "megacity": "mega shahar",
        "mountains": "togʻlar",
        "multicultural": "koʻp madaniyatli",
        "mysterious": "sirli",
        "orange": "olovrang",
        "originally": "asli",
        "pink": "pushti",
        "population": "aholi",
        "poverty": "qashshoqlik",
        "produce": "ishlab chiqarish",
        "public bath": "umumiy hammom",
        "quality": "sifat",
        "railway system": "temir yoʻl tizimi",
        "rainy": "yomgʻirli",
        "text": "matn",
        "sanitation": "sanitariya",
        "season": "fasl, fasl mavsumi",
        "shrine": "maqbara",
        "skyscrapers": "osmonoʻpar binolar",
        "slums": "xarobalar",
        "snacks": "gazaklar",
        "south": "janub",
        "spring": "bahor",
        "square": "maydon",
        "stone": "tosh",
        "subway system": "metro sistemasi",
        "sunrise": "quyosh chiqishi",
        "sunset": "quyosh botishi",
        "surrounded": "oʻralgan",
        "temple": "ibodatxona",
        "theatre": "teatr",
        "traditional": "milliy",
        "unique": "noyob",
        "up-to-date": "bugungi kungacha",
        "valley": "vodiy",
        "variety": "xilma-xil",
        "church": "cherkov",
        "hill": "tepalik",
        "historic": "tarixiy",
        "pollution": "ifloslanish",
        "river": "daryo",
        "toyshop": "oʻyinchoq doʻkoni",
        "wood": "yogʻoch",
        "pedestrian crossing": "piyodalar oʻtish joyi",
        "roundabout": "aylanma, chorraha",
        "traffic lights": "svetofor",
        "traffic sign": "yoʻl belgisi",
        "theory": "nazariya",
        "against": "qarshi",
        "beach": "sohil",
        "damage": "shikastlamoq",
        "discover": "kashf qilmoq",
        "emotion": "emotsiya",
        "fix": "tuzatmoq",
        "frank": "ochiq, samimiy",
        "identify": "tanib bilmoq",
        "island": "orol",
        "ocean": "okean",
        "perhaps": "ehtimol, balki",
        "pleasant": "yoqimli",
        "prevent": "toʻsqinlik qilmoq",
        "rock": "tosh",
        "save": "asramoq",
        "step": "qadam",
        "still": "hali ham",
        "taste": "ta'm",
        "throw": "uloqtirmoq",
        "wave": "toʻlqin",
        "benefit": "foyda",
        "certain": "ishonchi komil",
        "chance": "imkoniyat",
        "effect": "ta'sir",
        "essential": "juda muhim",
        "far": "uzoq",
        "focus": "diqqatni jamlamoq",
        "function": "vazifa",
        "grass": "maysa",
        "guard": "qoʻriqlamoq",
        "image": "rasm",
        "immediate": "tezkor",
        "primary": "birinchi",
        "proud": "faxrlangan",
        "remain": "qolmoq",
        "rest": "dam olmoq",
        "separate": "ajralgan",
        "site": "joy",
        "tail": "dum",
        "trouble": "muammo"
    },
    "Unit 10": {
        "Earth": "yer",
        "happen": "sodir boʻlmoq",
        "laptop": "noutbuk",
        "truth": "haqiqat",
        "detective": "detektiv, izquvar",
        "dress": "koʻylak",
        "romance": "romantika",
        "noise": "shovqin",
        "washing-up": "yuvish",
        "incredible": "aql bovar qilmas",
        "affect": "ta'sir qilish",
        "attached": "biriktirilgan",
        "below": "quyida, ostida",
        "bone": "suyak",
        "build": "qurmoq",
        "compartment": "boʻlim",
        "compete": "kurashmoq",
        "conditions": "holatlar",
        "decide": "qaror qilmoq",
        "develop": "rivojlanish",
        "effects": "ta'sirlar",
        "experiment": "tajriba",
        "fight": "urushmoq",
        "float": "suzmoq",
        "gravity": "tortishish kuchi",
        "instruments": "jihozlar",
        "laboratory": "laboratoriya",
        "long": "uzun",
        "muscle": "muskul",
        "orbit": "aylanmoq",
        "origin": "kelib chiqishi",
        "oxygen": "kislorod",
        "planet": "sayyora",
        "preparation": "tayyorgarlik",
        "research": "izlanish, tadqiqot",
        "sauce": "sous, qayla",
        "shorts": "shortik",
        "spicy": "achchiq",
        "spoon": "qoshiq",
        "star": "yulduz",
        "supplies": "ta'minot",
        "T-shirt": "futbolka",
        "taste": "ta'm",
        "tin": "konserva qutisi",
        "universe": "koinot",
        "actor": "aktyor",
        "alike": "oʻxshash",
        "blond": "sargʻish",
        "blue": "koʻk",
        "boots": "etiklar",
        "brown": "jigarrang",
        "coat": "palto",
        "dark": "qorongʻu",
        "glasses": "koʻzoynak",
        "good-looking": "xushbichim",
        "handsome": "kelishgan",
        "hat": "shlyapa",
        "identical": "bir xil",
        "pretty": "goʻzal",
        "purple": "siyohrang",
        "scarf": "sharf",
        "shoes": "oyoq kiyim",
        "short": "kalta",
        "skirt": "yubka",
        "suit": "kostyum",
        "tall": "baland",
        "trainers": "krossovka",
        "twins": "egizaklar",
        "unusual": "noodatiy",
        "bankholiday": "qoʻshimcha rasmiy ta'til",
        "couple": "juft, ikki",
        "message": "xabar",
        "nevermind": "hechqisi yoʻq",
        "switchon": "yoqmoq",
        "anymore": "boshqa, ortiq",
        "asleep": "uyquda",
        "berry": "meva, rezavor",
        "collect": "toʻplamoq",
        "conversation": "suhbat",
        "creature": "mavjudot",
        "decision": "qaror",
        "either": "ikkisidan biri",
        "forest": "oʻrmon",
        "ground": "yer",
        "marry": "turmush qurmoq",
        "prepare": "tayyorlanmoq",
        "sail": "qayiqda suzmoq",
        "serious": "jiddiy",
        "spend": "oʻtkazmoq, sarflamoq",
        "strange": "noodatiy",
        "wake": "uygʻonmoq",
        "alone": "yolgʻiz",
        "apartment": "kvartira",
        "article": "maqola",
        "artist": "rassom",
        "attitude": "munosabat",
        "compare": "taqqoslamoq",
        "judge": "baho bermoq",
        "magazine": "jurnal",
        "meal": "taom",
        "method": "usul",
        "neighbor": "qoʻshni",
        "professional": "kasbiy",
        "profit": "foyda",
        "quality": "sifat",
        "shape": "shakli",
        "space": "boʻsh joy, kosmos",
        "stair": "zina",
        "symbol": "belgi",
        "thin": "ozgʻin, yupqa"
    },
    "Unit 11": {
        "fortunate": "omadli",
        "happen": "sodir boʻlmoq",
        "length": "uzunlik",
        "mistake": "xato",
        "observe": "kuzatmoq",
        "opportunity": "imkoniyat",
        "prize": "sovgʻa",
        "race": "poyga",
        "realize": "tushunmoq",
        "respond": "javob bermoq",
        "risk": "xavf",
        "wonder": "ajablanmoq",
        "yet": "hali ham",
        "do the washing": "yuvish",
        "future": "kelajak",
        "grow up": "ulgʻaymoq",
        "payrise": "maosh oshirish",
        "plan": "reja tuzish",
        "retire": "nafaqaga chiqish",
        "soon": "tez orada",
        "drop": "tushirib yuborish",
        "due": "kutilgan",
        "fall": "yiqilmoq, tushmoq",
        "kiss": "oʻpich",
        "sneeze": "aksirish",
        "climb": "chiqmoq, zabt etmoq",
        "cruise": "dengiz sayohati",
        "pyramids": "piramida",
        "safari": "safar",
        "colourful": "rang-barang",
        "frightened": "qoʻrqqan",
        "hire": "yollamoq",
        "peaceful": "tinch",
        "thunder": "chaqmoq",
        "backpack": "ryugzak, sumka",
        "carry": "koʻtarib yurmoq",
        "fields": "ochiq maydon",
        "folksong": "folklor musiqa",
        "freedom": "ozodlik",
        "harmony": "uygʻunlik, hamjihatlik",
        "hat": "shlyapa",
        "hospitality": "mehmondoʻstlik",
        "human": "insoniy",
        "jacket": "jaket",
        "passers-by": "yoʻlovchilar",
        "perfect": "mukammal",
        "podcasts": "podkastlar",
        "sign": "belgi, ishora",
        "smile": "tabassum qilmoq",
        "stressful": "stressli",
        "suitcase": "chamadon",
        "supper": "kechki ovqat",
        "Wales": "Uels",
        "walking stick": "hassa",
        "website": "veb sayt",
        "storm": "boʻron",
        "picnic": "piknik",
        "blood": "qon",
        "burn": "yonmoq",
        "contain": "ichiga olmoq",
        "correct": "toʻgʻri",
        "crop": "hosil",
        "demand": "talab etmoq",
        "equal": "teng",
        "hole": "teshik",
        "increase": "koʻpaymoq",
        "owe": "qarzdor boʻlmoq",
        "position": "pozitsiya",
        "raise": "koʻtarmoq",
        "responsible": "mas'uliyatli",
        "sight": "koʻrinish, nigoh",
        "spot": "nuqta",
        "structure": "tuzilish",
        "whole": "butun",
        "coach": "murabbiy",
        "description": "tavsif",
        "direct": "toʻgʻridan-toʻgʻri",
        "exam": "imtihon",
        "example": "misol",
        "limit": "chegara",
        "local": "mahalliy",
        "magical": "sehrli",
        "mail": "xabar, pochta",
        "novel": "roman",
        "poet": "shoir",
        "print": "chop etmoq",
        "scene": "lavha, sahna",
        "sheet": "varoq",
        "silly": "ahmoqona",
        "store": "doʻkon",
        "suffer": "aziyat chekmoq",
        "technology": "texnologiya",
        "across": "boʻylab",
        "breathe": "nafas olmoq",
        "characteristic": "xususiyat",
        "consume": "iste'mol qilmoq",
        "excite": "hayajonlantirmoq",
        "extreme": "keskin, oʻta",
        "fear": "qoʻrquv"
    },
    "Unit 12": {
        "advice": "maslahat",
        "brave": "botir (dovyurak)",
        "crown": "toj",
        "entrance": "kirish joyi",
        "fault": "xato (ayb)",
        "fool": "ahmoq",
        "include": "ichiga olmoq",
        "least": "eng kam",
        "miserable": "baxtsiz",
        "opinion": "fikr",
        "raw": "xom",
        "religion": "din",
        "shame": "sharmandalik (uyat)",
        "tradition": "an'ana",
        "trick": "fokus (xiyla)",
        "wind": "shamol",
        "audience": "auditoriya (tomoshabinlar)",
        "celebrate": "nishonlamoq",
        "ceremony": "marosim",
        "commercial": "tijoriy (reklama)",
        "culture": "madaniyat",
        "custom": " urf-odat",
        "festive": "bayramona",
        "fireworks": "salut (mushakbozlik)",
        "gather": "toʻplanmoq",
        "parade": "parad",
        "relationship": "munosabat",
        "spectacular": "ajoyib (goʻzal)",
        "sponsor": "homiy",
        "symbol": "belgi (ramz)",
        "clown": "masharaboz",
        "drums": "baraban",
        "festival": "festival",
        "mask": "niqob",
        "scary": "qoʻrqinchli",
        "stage": "sahna",
        "costume": "kostyum",
        "float": "koʻchma sahna (platforma)",
        "makeup": "grim (makiyaj)",
        "musical": "musiqiy",
        "performer": "ijrochi",
        "chilli": "achchiq qalampir",
        "garlic": "sarimsoq piyoz",
        "ginger": "zanjabil",
        "lemon": "limon",
        "melon": "qovun",
        "nuts": "yongʻoqlar",
        "onion": "piyoz",
        "potato": "kartoshka",
        "prawns": "krevetkalar",
        "salt": "tuz",
        "soup": "shoʻrva",
        "spinach": "ismaloq",
        "steak": "steyk (goʻsht)",
        "vanilla": "vanil",
        "bacon": "bekon (choʻchqa goʻshti)",
        "beef": "mol goʻshti",
        "butter": "sariyogʻ",
        "cabbage": "karam",
        "cream": "qaymoq (krem)",
        "lettuce": "salat bargi",
        "mushrooms": "qoʻziqorinlar",
        "oil": "oʻsimlik yogʻi",
        "peas": "noʻxat",
        "turkey": "kurka goʻshti",
        "acrobat": "akrobat",
        "alternative": "alternativ (tanlov)",
        "atmosphere": "atmosfera",
        "baking": "pishirish (pishiriq)",
        "behaviour": "xulq-atvor",
        "belong": "tegishli boʻlmoq",
        "bury": "koʻmmoq",
        "clay": "loyxok (loy)",
        "comfort": "tasalli (shinamlik)",
        "complain": "shikoyat qilmoq",
        "connection": "aloqa",
        "copper": "mis",
        "cotton": "paxta",
        "criticize": "tanqid qilmoq",
        "deserve": "loyiq boʻlmoq",
        "diet": "parhez (ratsion)",
        "disappointed": "hafsalasi pir boʻlgan",
        "display": "koʻrgazma (namoyish)",
        "documentary": "hujjatli film",
        "escape": "qochib qutulmoq",
        "festivities": "bayram tadbirlari",
        "fictional": "toʻqima (badiiy)",
        "flavour": "maza (ta'm)",
        "fry": "qovurmoq",
        "giant": "ulkan (gigant)",
        "glove": "qoʻlqop",
        "history": "tarix",
        "hometown": "ona shahar (tugʻilgan joy)",
        "ingredient": "ingredient (tarkibiy qism)",
        "international": "xalqaro",
        "juice": "sharbat (sok)",
        "leather": "teri",
        "literature": "adabiyot",
        "magician": "sehrgar (boshqotirmachi)",
        "mix": "aralashtirmoq",
        "monster": "mahluq",
        "origin": "kelib chiqishi",
        "original": "asliy (original)",
        "outdoor": "ochiq havodagi",
        "outstanding": "ajoyib (juda yaxshi)",
        "percentage": "foiz miqdori",
        "performance": "ijro (tomosha)",
        "permission": "ruxsat",
        "plastic": "plastik",
        "pot": "tuvak (idish)",
        "praise": "maqtamoq",
        "prepare": "tayyorlanmoq",
        "pretend": "oʻzinigday koʻrsatmoq",
        "pudding": "puding",
        "recipe": "retsept",
        "relative": "qarindosh",
        "sculpture": "haykal (skulptura)",
        "serve": "xizmat koʻrsatmoq (tortmoq)",
        "silk": "ipak",
        "silver": "kumush",
        "skeleton": "skelet",
        "soluble": "eruvchan",
        "spectacle": "tomosha",
        "spectator": "tomoshabin",
        "spill": "toʻkib yubormoq",
        "string": "ip (arqon)",
        "stylish": "zamonaviy (bichimli)",
        "substance": "modda",
        "suit": "kostyum (mos kelmoq)",
        "surface": "yuza (sirt)",
        "taste": "ta'm (tatib koʻrmoq)",
        "tasty": "shirin (mazali)",
        "theatre": "teatr",
        "typical": "odatiy (har doimgi)",
        "unfortunate": "afsuslanarli (omadsiz)",
        "visual": "vizual (koʻrgazmali)",
        "wool": "jun"
    }
}
